function [settings]=setDefaultFunctions(settings)
%Allow modular selection of certain functions
function_alternative = [ ...
    struct( 'name', 'getBestMatch', 'default', 'getBestMatchSSD_3color_dwc'), ...
    struct( 'name', 'getNextBestMatch', 'default', 'getNextBestMatchSSD' ), ...
    struct( 'name', 'createAdaptivePatch', 'default', 'createAdaptivePatchB_weighted_3color_FullAmoeba' ), ...
    struct( 'name', 'matchDistanceFunction', 'default', 'getMatchPriorityOnlyOutsideTarget' ), ...
    struct( 'name', 'blendDistanceFunction', 'default', 'getBlendPriorityOnlyOutsideTarget' ), ...
    struct( 'name', 'calculatePriority', 'default', 'calculatePriority_weighted_FullAmoeba' ), ...
    struct( 'name', 'FillIn','default', 'FillIn_ShiftWholeImage') ...
    ];

for f = 1:numel(function_alternative)
    fieldname = function_alternative(f).name;
    functioninfo = sprintf('%s_INFO', fieldname);
    if ~isfield(settings, fieldname)
        settings.(fieldname) = function_alternative(f).default;
    end
    settings.(functioninfo) = help(settings.(fieldname));
end

